"""Turning a profile into the files the dedicated server actually reads.

Two files are produced inside the profile's ``fs_homepath/q3ut4`` directory:

``<profile>.cfg``
    Every setting, written as ``set``/``sets`` lines and ending with the start
    map, mirroring the layout of the shipped ``server_example.cfg``.

``<mapcycle>.txt``
    One map per line.

Values are quoted and sanitised. A stray quote or newline in a hostname would
otherwise truncate the config or inject an unintended command, and semicolons
separate commands in the Quake 3 console.
"""

from __future__ import annotations

from pathlib import Path

from .. import paths
from ..model import cvars, maps
from ..model.profile import Profile
from .httpd import local_ip

#: Characters that would break out of a quoted config value.
_UNSAFE = str.maketrans({'"': "'", "\n": " ", "\r": " ", ";": ","})

HEADER = """\
// Generated by Urban Terror Server Manager -- do not edit by hand.
// Changes made here are overwritten the next time this server starts.
// Profile: {name}
"""


def sanitise(value: str) -> str:
    """Make a value safe to place inside a quoted config directive."""
    return str(value).translate(_UNSAFE)


def cvar_token(name: str) -> str:
    """Render a cvar name for a config directive.

    ``" Admin"`` and ``" Email"`` carry a deliberate leading space so they sort
    to the top of the server browser's details. Written bare the space is eaten
    by the tokeniser and the value lands on a different cvar, so names with
    whitespace are quoted -- which is how server_example.cfg writes them too.
    """
    return f'"{name}"' if name != name.strip() or " " in name else name


def download_url(profile: Profile) -> str:
    """The ``sv_dlURL`` for a profile using the built-in download server.

    Computed here rather than stored on the profile. A stored URL goes stale the
    moment the machine's address changes or the download server stops, and the
    server would keep advertising an address nothing answers on -- which looks
    to a joining player exactly like a broken custom map.
    """
    return f"http://{profile.dl_host or local_ip()}:{profile.dl_port}"


def render_cfg(profile: Profile) -> str:
    """The full text of the server config for a profile."""
    lines: list[str] = [HEADER.format(name=sanitise(profile.name))]
    gametype = profile.gametype

    for group in cvars.GROUPS:
        entries = [
            c for c in cvars.for_group(group.key, gametype)
            if c.name not in cvars.COMMAND_LINE_ONLY
            and c.kind is not cvars.Kind.MAPCYCLE
        ]
        if not entries:
            continue

        body: list[str] = []
        for cvar in entries:
            if cvar.name == "sv_dlURL" and profile.dl_enabled:
                value = download_url(profile)
            else:
                value = cvar.to_cfg_value(profile.get(cvar.name))
            body.append(f'{cvar.setter} {cvar_token(cvar.name)} "{sanitise(value)}"')

        lines.append("")
        lines.append(f"// ---- {group.title} " + "-" * max(0, 56 - len(group.title)))
        lines.extend(body)

    # The map cycle cvar names a file rather than holding the rotation.
    cycle_cvar = cvars.get("g_mapcycle")
    if cycle_cvar and profile.mapcycle:
        lines.append("")
        lines.append("// ---- Map Cycle " + "-" * 47)
        lines.append(f'set g_mapcycle "{mapcycle_filename(profile)}"')

    # Settings the registry does not know about, preserved from an import.
    if profile.extra_cfg.strip():
        lines.append("")
        lines.append("// ---- Custom directives (preserved from import) ----------")
        lines.extend(profile.extra_cfg.replace("\r", "").splitlines())

    start = sanitise(profile.start_map or "ut4_casa")
    lines.append("")
    lines.append("// ---- Start " + "-" * 51)
    lines.append(f"map {start}")
    lines.append("")
    return "\n".join(lines)


def cfg_filename(profile: Profile) -> str:
    return f"utsm_{profile.id}.cfg"


def mapcycle_filename(profile: Profile) -> str:
    return f"utsm_{profile.id}_cycle.txt"


def write(profile: Profile) -> Path:
    """Write a profile's config and map cycle, returning the config path.

    Files land in the profile's own ``fs_homepath``, never in the game install,
    which on a packaged Linux setup is root-owned and read-only.
    """
    mod_dir = paths.profile_mod_dir(profile.id)
    mod_dir.mkdir(parents=True, exist_ok=True)

    cfg_path = mod_dir / cfg_filename(profile)
    cfg_path.write_text(render_cfg(profile), encoding="utf-8")

    if profile.mapcycle:
        cycle_path = mod_dir / mapcycle_filename(profile)
        cycle_path.write_text(maps.render_cycle(profile.mapcycle), encoding="utf-8")

    return cfg_path


def launch_args(profile: Profile, install_basepath: Path) -> list[str]:
    """Command-line arguments for the dedicated server.

    ``fs_basepath`` points at the read-only game install for the .pk3 data;
    ``fs_homepath`` is the profile's private directory, which the engine
    searches first, so the generated config is found there.
    """
    return [
        "+set", "fs_basepath", str(install_basepath),
        "+set", "fs_homepath", str(paths.profile_home(profile.id)),
        "+set", "fs_game", paths.MOD_DIR,
        "+set", "dedicated", str(int(profile.get("dedicated") or 2)),
        "+set", "net_port", str(profile.net_port),
        # Only takes effect here; a config assignment is silently discarded.
        # See cvars.COMMAND_LINE_ONLY.
        "+set", "sv_allowdownload", "1" if profile.get("sv_allowdownload") else "0",
        "+exec", cfg_filename(profile),
    ]
